
    const products = [
        {
            id: 1,
            title: "Realme GT6 256GB",
            price: "₹33999",
            description: "Superfast Snapdragon processor | 5G support",
            image: "../assets/realme-gt6.jpg",
        },
        {
            id: 2,
            title: "Realme 13 Pro",
            price: "₹22999",
            description: "6.7-inch display | 128GB Storage | 5G support",
            image: "../assets/realme-13-pro.jpg",
        },
        {
            id: 3,
            title: "Realme NARZO N61",
            price: "₹10999",
            description: "90Hz Eye Comfort Display | IP54 Dust & Water Resistance | 48-Month Fluency | Charger in The Box",
            image: "../assets/realme-narzo-n61.jpg",
        },
        {
            id: 4,
            title: "Realme 13 5G",
            price: "₹22999",
            description: "Latest 5G smartphone with powerful performance",
            image: "../assets/realme-13-5g.jpg",
        },
        {
            id: 5,
            title: "Realme GT6 256GB (6.7 inch)",
            price: "₹34999",
            description: "Superfast Snapdragon processor | 5G support",
            image: "../assets/realme-gt6.jpg",
        },
        {
            id: 6,
            title: "Realme C63 4G (8GB RAM, 256GB Storage)",
            price: "₹14999",
            description: "6.7-inch display | High Performance | Long Battery Life",
            image: "../assets/realme-c63.jpg",
        },
        {
            id: 7,
            title: "Realme GT Neo 3",
            price: "₹31999",
            description: "Ultra-fast 5G | 120Hz AMOLED | Snapdragon 888",
            image: "../assets/realme-gt-neo3.jpg",
        },
        {
            id: 8,
            title: "Oppo A3",
            price: "₹17999",
            description: "6.2-inch Full HD+ display | MediaTek Helio P60 | 4GB RAM",
            image: "../assets/oppo-a3.jpg",
        },
        {
            id: 9,
            title: "OPPO Reno12 5G",
            price: "₹28999",
            description: "6.5-inch AMOLED | 5G Support | 8GB RAM + 256GB Storage",
            image: "../assets/oppo-reno-12.jpg",
        },
        {
            id: 10,
            title: "OPPO Reno8 5G",
            price: "₹33499",
            description: "OLED Display | 5G | 12GB RAM | 256GB Storage",
            image: "../assets/oppo-reno8-5g.jpg",
        },
        {
            id: 11,
            title: "OPPO A58 (8GB RAM, 128GB Storage)",
            price: "₹17499",
            description: "6.5-inch Display | 5G Ready | Long Battery Life",
            image: "../assets/oppo-a58.jpg",
        },
        {
            id: 12,
            title: "Vivo Y71",
            price: "₹7699",
            description: "6.2-inch display | MediaTek Helio P60 | 4GB RAM",
            image: "../assets/vivo-old-phone.jpg",
        },
        {
            id: 13,
            title: "MI 5A",
            price: "₹4999",
            description: "Affordable smartphone with essential features.",
            image: "../assets/mi-old-phone.jpg",
        },
        {
            id: 14,
            title: "Realme C1 (32, 64GB)",
            price: "₹4599",
            description: "Budget-friendly smartphone with decent performance.",
            image: "../assets/realme-old-phone.jpg",
        },
        {
            id: 15,
            title: "Oppo A37",
            price: "₹5499",
            description: "Compact smartphone with good battery life.",
            image: "../assets/oppo-old-phone.jpg",
        },
        {
            id: 16,
            title: "Vivo Y71",
        price: "₹6299",
        description: "Affordable smartphone with essential features.",
        image: "../assets/vivo-old-phone.jpg",
    },
    {
        id: 17,
        title: "Vivo Y40 PRO",
        price: "₹9299",
        description: "High-performance smartphone with a sleek design.",
        image: "../assets/vivo-v40-pro.jpg",
    },
    {
        id: 18,
        title: "Vivo Y200e 5G",
        price: "₹8299",
        description: "5G smartphone with advanced features.",
        image: "../assets/Vivo Y200e 5G.jpg",
    },
];

// Export the products array for use in other modules
export default products;